set(OLD_SUBMODULE ${SUBMODULE})
set(SUBMODULE "GRAPHICS_COMMON_MATH")
set(${SUBMODULE} ${SUBMODULE})

file(GLOB ${SUBMODULE}_SOURCE
    ${CMAKE_CURRENT_LIST_DIR}/source/*)

file(GLOB ${SUBMODULE}_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/include/*)

set(${SUBMODULE}_FILES ${${SUBMODULE}_SOURCE} ${${SUBMODULE}_HEADERS})
set(${SUBMODULE}_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/include)

set(SUBMODULE ${OLD_SUBMODULE})
